export interface Kamar {
  id: number;
  slug: string;
  nama: string;
  tipe: string;
  penghuni: "Putra" | "Putri" | "Campur";
  lokasi: string;
  kota: string;
  alamat: string;
  harga: number;
  harga3Bulan: number;
  harga6Bulan: number;
  hargaHarian?: number;
  tersedia: number;
  deskripsi: string;
  fasilitas: string[];
  peraturan: string[];
  gambar: string;
  gambarList: string[];
  whatsapp: string;
}

export interface Artikel {
  id: number;
  judul: string;
  slug: string;
  tanggal: string;
  kategori: string;
  ringkasan: string;
  gambar: string;
  penulis: string;
}

export const kamarList: Kamar[] = [
  {
    id: 1,
    slug: "dzawani-kost-rajawali",
    nama: "Dzawani Kost Rajawali",
    tipe: "Deluxe",
    penghuni: "Putri",
    lokasi: "Condongcatur, Sleman",
    kota: "Yogyakarta",
    alamat: "Jl. Rajawali, Condongcatur, Sleman, DIY",
    harga: 2100000,
    harga3Bulan: 6000000,
    harga6Bulan: 11500000,
    hargaHarian: 250000,
    tersedia: 5,
    deskripsi: "Kost eksklusif khusus putri di kawasan Rajawali Condongcatur. Fasilitas lengkap dengan keamanan 24 jam, WiFi cepat, dan suasana yang nyaman untuk mahasiswi maupun pekerja.",
    fasilitas: ["AC", "Kasur Spring Bed", "Kamar Mandi Dalam", "WiFi Gratis", "Parkir Motor", "Keamanan 24 Jam", "CCTV", "Laundry", "Dapur Bersama"],
    peraturan: ["Khusus penghuni putri.", "Dilarang membawa tamu lawan jenis ke dalam kamar.", "Dilarang merokok di dalam kamar.", "Pembayaran wajib tepat waktu.", "Jam bertamu maksimal pukul 22.00 WIB.", "Jaga kebersihan bersama."],
    gambar: "https://dzawanikost.com/wp-content/uploads/2022/12/DSC02849-1.jpg",
    gambarList: [
      "https://dzawanikost.com/wp-content/uploads/2022/12/DSC02849-1.jpg",
      "https://dzawanikost.com/wp-content/uploads/2023/01/DSC02857.jpg",
      "https://dzawanikost.com/wp-content/uploads/2022/12/DSC02835.jpg",
      "https://dzawanikost.com/wp-content/uploads/2022/10/DSC05147.jpg",
      "https://dzawanikost.com/wp-content/uploads/2022/10/DSC05190.jpg",
    ],
    whatsapp: "6281234567890",
  },
  {
    id: 2,
    slug: "dzawani-kost-condongcatur",
    nama: "Dzawani Kost Condongcatur",
    tipe: "Deluxe",
    penghuni: "Campur",
    lokasi: "Condongcatur, Depok",
    kota: "Yogyakarta",
    alamat: "Condongcatur, Depok, Sleman, DIY",
    harga: 1700000,
    harga3Bulan: 4900000,
    harga6Bulan: 9400000,
    tersedia: 4,
    deskripsi: "Kost eksklusif di Condongcatur dengan fasilitas modern. Dekat dengan berbagai kampus dan pusat perbelanjaan. Cocok untuk mahasiswa dan karyawan.",
    fasilitas: ["AC", "Kasur Spring Bed", "Kamar Mandi Dalam", "WiFi Gratis", "Parkir Motor & Mobil", "Keamanan 24 Jam", "CCTV", "Laundry", "Mushola"],
    peraturan: ["Dilarang membawa tamu lawan jenis ke dalam kamar.", "Dilarang merokok di dalam kamar.", "Pembayaran wajib tepat waktu.", "Jam bertamu maksimal pukul 22.00 WIB.", "Jaga kebersihan bersama."],
    gambar: "https://dzawanikost.com/wp-content/uploads/2023/08/DSC02835.jpg",
    gambarList: [
      "https://dzawanikost.com/wp-content/uploads/2023/08/DSC02835.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/05/DSC02825.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/05/DSC02837.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/05/DSC02854.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/05/DSC02855.jpg",
    ],
    whatsapp: "6281234567890",
  },
  {
    id: 3,
    slug: "dzawani-kost-ngabean",
    nama: "Dzawani Kost Ngabean",
    tipe: "Superior",
    penghuni: "Putri",
    lokasi: "Ngabean, Wirobrajan",
    kota: "Yogyakarta",
    alamat: "Jl. Ngabean, Wirobrajan, Yogyakarta",
    harga: 1500000,
    harga3Bulan: 4300000,
    harga6Bulan: 8200000,
    hargaHarian: 250000,
    tersedia: 6,
    deskripsi: "Kost eksklusif Ngabean dengan berbagai pilihan tipe kamar. Lokasi strategis di pusat kota Yogyakarta, dekat Malioboro dan berbagai fasilitas umum.",
    fasilitas: ["AC", "Kasur Spring Bed", "Kamar Mandi Dalam", "WiFi Gratis", "Parkir Motor", "Keamanan 24 Jam", "CCTV", "Dapur Bersama", "Ruang Santai"],
    peraturan: ["Khusus penghuni putri.", "Dilarang membawa tamu lawan jenis ke dalam kamar.", "Dilarang merokok di dalam kamar.", "Pembayaran wajib tepat waktu.", "Jam bertamu maksimal pukul 22.00 WIB."],
    gambar: "https://dzawanikost.com/wp-content/uploads/2024/07/DSC00571.jpg",
    gambarList: [
      "https://dzawanikost.com/wp-content/uploads/2024/07/DSC00571.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/07/DSC00573.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/07/DSC00580.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/07/DSC02849.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/07/DSC02857.jpg",
    ],
    whatsapp: "6281234567890",
  },
  {
    id: 4,
    slug: "dzawani-kost-palagan",
    nama: "Dzawani Kost Palagan",
    tipe: "Premium",
    penghuni: "Campur",
    lokasi: "Palagan Tentara Pelajar",
    kota: "Yogyakarta",
    alamat: "Jl. Palagan Tentara Pelajar, Sleman, DIY",
    harga: 1650000,
    harga3Bulan: 4700000,
    harga6Bulan: 9000000,
    tersedia: 3,
    deskripsi: "Kost mewah di kawasan Palagan dengan fasilitas premium. Tersedia untuk putra, putri, maupun pasutri. Lingkungan tenang dan nyaman.",
    fasilitas: ["AC", "Kasur Spring Bed", "Kamar Mandi Dalam", "WiFi Gratis", "Parkir Motor & Mobil", "Keamanan 24 Jam", "CCTV", "Kolam Renang", "Gym", "Laundry"],
    peraturan: ["Dilarang membawa tamu lawan jenis ke dalam kamar.", "Dilarang merokok di dalam kamar.", "Pembayaran wajib tepat waktu.", "Jam bertamu maksimal pukul 22.00 WIB.", "Jaga kebersihan bersama."],
    gambar: "https://dzawanikost.com/wp-content/uploads/2024/04/DSC04539-2-2.jpg",
    gambarList: [
      "https://dzawanikost.com/wp-content/uploads/2024/04/DSC04539-2-2.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/04/DSC04582-2-2.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/04/DSC04591-2-2.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/04/DSC04600-2-2.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/04/DSC04617-2-2.jpg",
    ],
    whatsapp: "6281234567890",
  },
  {
    id: 5,
    slug: "dzawani-kost-pogung",
    nama: "Dzawani Kost Pogung",
    tipe: "Premium",
    penghuni: "Campur",
    lokasi: "Pogung Rejo, Sinduadi",
    kota: "Yogyakarta",
    alamat: "Jl. Pogung Rejo, Sinduadi, Mlati, Sleman, DIY",
    harga: 2000000,
    harga3Bulan: 5700000,
    harga6Bulan: 10800000,
    tersedia: 2,
    deskripsi: "Kost premium di kawasan Pogung dekat UGM dan UNY. Fasilitas lengkap dengan kamar yang luas dan nyaman untuk mahasiswa dan pekerja.",
    fasilitas: ["AC", "Kasur Spring Bed", "Kamar Mandi Dalam", "WiFi Gratis", "Parkir Motor & Mobil", "Keamanan 24 Jam", "CCTV", "Laundry", "Dapur Bersama", "Ruang Belajar"],
    peraturan: ["Dilarang membawa tamu lawan jenis ke dalam kamar.", "Dilarang merokok di dalam kamar.", "Pembayaran wajib tepat waktu.", "Jam bertamu maksimal pukul 22.00 WIB.", "Jaga kebersihan bersama."],
    gambar: "https://dzawanikost.com/wp-content/uploads/2024/09/DSC02830.jpg",
    gambarList: [
      "https://dzawanikost.com/wp-content/uploads/2024/09/DSC02830.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/09/DSC02835.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/09/DSC02842.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/09/DSC04725.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/09/DSC04771.jpg",
    ],
    whatsapp: "6281234567890",
  },
  {
    id: 6,
    slug: "dzawani-kost-krawitan",
    nama: "Dzawani Kost Krawitan",
    tipe: "Standard",
    penghuni: "Putra",
    lokasi: "Krawitan, Godean",
    kota: "Yogyakarta",
    alamat: "Krawitan, Godean, Sleman, DIY",
    harga: 700000,
    harga3Bulan: 1950000,
    harga6Bulan: 3700000,
    tersedia: 8,
    deskripsi: "Kost khusus putra di kawasan Krawitan Godean. Harga terjangkau dengan fasilitas yang memadai. Cocok untuk mahasiswa dengan budget terbatas.",
    fasilitas: ["WiFi Gratis", "Kamar Mandi Luar", "Parkir Motor", "Keamanan", "Dapur Bersama"],
    peraturan: ["Khusus penghuni putra.", "Dilarang merokok di dalam kamar.", "Pembayaran wajib tepat waktu.", "Jam bertamu maksimal pukul 22.00 WIB.", "Jaga kebersihan bersama."],
    gambar: "https://dzawanikost.com/wp-content/uploads/2022/09/DSC02839.jpg",
    gambarList: [
      "https://dzawanikost.com/wp-content/uploads/2022/09/DSC02839.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/05/DSC04722.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/05/DSC05148.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/05/DSC05156.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/05/DSC05164.jpg",
    ],
    whatsapp: "6281234567890",
  },
  {
    id: 7,
    slug: "dzawani-kost-sambilegi",
    nama: "Dzawani Kost Sambilegi",
    tipe: "Standard",
    penghuni: "Campur",
    lokasi: "Sambilegi, Maguwoharjo",
    kota: "Yogyakarta",
    alamat: "Sambilegi, Maguwoharjo, Depok, Sleman, DIY",
    harga: 900000,
    harga3Bulan: 2550000,
    harga6Bulan: 4900000,
    tersedia: 7,
    deskripsi: "Kost di kawasan Sambilegi Maguwoharjo dengan harga terjangkau. Dekat bandara dan berbagai fasilitas umum.",
    fasilitas: ["AC", "Kasur Spring Bed", "Kamar Mandi Dalam", "WiFi Gratis", "Parkir Motor", "Keamanan 24 Jam"],
    peraturan: ["Dilarang membawa tamu lawan jenis ke dalam kamar.", "Dilarang merokok di dalam kamar.", "Pembayaran wajib tepat waktu.", "Jam bertamu maksimal pukul 22.00 WIB."],
    gambar: "https://dzawanikost.com/wp-content/uploads/2024/07/DSC04719.jpg",
    gambarList: [
      "https://dzawanikost.com/wp-content/uploads/2024/07/DSC04719.jpg",
      "https://dzawanikost.com/wp-content/uploads/2023/08/DSC04713.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/01/DSC04835.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/01/DSC04843.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/12/DSC02845.jpg",
    ],
    whatsapp: "6281234567890",
  },
  {
    id: 8,
    slug: "dzawani-kost-pancanaka",
    nama: "Dzawani Kost Pancanaka",
    tipe: "Deluxe",
    penghuni: "Putri",
    lokasi: "Pancanaka, Sleman",
    kota: "Yogyakarta",
    alamat: "Pancanaka, Sleman, DIY",
    harga: 1900000,
    harga3Bulan: 5400000,
    harga6Bulan: 10300000,
    tersedia: 3,
    deskripsi: "Kost eksklusif putri di kawasan Pancanaka Sleman. Fasilitas premium dengan berbagai pilihan tipe kamar dari standar hingga deluxe.",
    fasilitas: ["AC", "Kasur Spring Bed", "Kamar Mandi Dalam", "WiFi Gratis", "Parkir Motor & Mobil", "Keamanan 24 Jam", "CCTV", "Kolam Renang", "Laundry"],
    peraturan: ["Khusus penghuni putri.", "Dilarang membawa tamu lawan jenis ke dalam kamar.", "Dilarang merokok di dalam kamar.", "Pembayaran wajib tepat waktu.", "Jam bertamu maksimal pukul 22.00 WIB."],
    gambar: "https://dzawanikost.com/wp-content/uploads/2024/12/DSC00571.jpg",
    gambarList: [
      "https://dzawanikost.com/wp-content/uploads/2024/12/DSC00571.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/12/DSC00581.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/11/DSC04771.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/11/DSC05157.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/10/DSC00571.jpg",
    ],
    whatsapp: "6281234567890",
  },
  {
    id: 9,
    slug: "dzawani-kost-metro-bandung",
    nama: "Dzawani Kost Metro Bandung",
    tipe: "Deluxe",
    penghuni: "Putri",
    lokasi: "Metro, Bandung",
    kota: "Bandung",
    alamat: "Metro, Bandung, Jawa Barat",
    harga: 1500000,
    harga3Bulan: 4300000,
    harga6Bulan: 8200000,
    hargaHarian: 250000,
    tersedia: 4,
    deskripsi: "Kost eksklusif putri di kawasan Metro Bandung. Fasilitas lengkap dengan lokasi strategis dekat pusat kota Bandung.",
    fasilitas: ["AC", "Kasur Spring Bed", "Kamar Mandi Dalam", "WiFi Gratis", "Parkir Motor", "Keamanan 24 Jam", "CCTV", "Laundry"],
    peraturan: ["Khusus penghuni putri.", "Dilarang membawa tamu lawan jenis ke dalam kamar.", "Dilarang merokok di dalam kamar.", "Pembayaran wajib tepat waktu."],
    gambar: "https://dzawanikost.com/wp-content/uploads/2023/09/DSC06243.jpg",
    gambarList: [
      "https://dzawanikost.com/wp-content/uploads/2023/09/DSC06243.jpg",
      "https://dzawanikost.com/wp-content/uploads/2023/09/DSC07235-1.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/08/DSC00571.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/08/DSC00581.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/08/DSC00581-1.jpg",
    ],
    whatsapp: "6281234567890",
  },
  {
    id: 10,
    slug: "dzawani-kost-unjani-bandung",
    nama: "Dzawani Kost Unjani Bandung",
    tipe: "Premium",
    penghuni: "Putri",
    lokasi: "Dekat Unjani, Cimahi",
    kota: "Bandung",
    alamat: "Cimahi, Bandung, Jawa Barat",
    harga: 1800000,
    harga3Bulan: 5100000,
    harga6Bulan: 9800000,
    tersedia: 3,
    deskripsi: "Kost eksklusif putri dekat Universitas Jenderal Achmad Yani (Unjani) Bandung. Fasilitas premium untuk mahasiswi.",
    fasilitas: ["AC", "Kasur Spring Bed", "Kamar Mandi Dalam", "WiFi Gratis", "Parkir Motor", "Keamanan 24 Jam", "CCTV", "Laundry", "Dapur Bersama"],
    peraturan: ["Khusus penghuni putri.", "Dilarang membawa tamu lawan jenis ke dalam kamar.", "Dilarang merokok di dalam kamar.", "Pembayaran wajib tepat waktu."],
    gambar: "https://dzawanikost.com/wp-content/uploads/2024/01/DSC02825.jpg",
    gambarList: [
      "https://dzawanikost.com/wp-content/uploads/2024/01/DSC02825.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/01/DSC02825-1.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/01/DSC02837-1.jpg",
      "https://dzawanikost.com/wp-content/uploads/2024/01/DSC04713-1.jpg",
      "https://dzawanikost.com/wp-content/uploads/2023/08/DSC04725-1.jpg",
    ],
    whatsapp: "6281234567890",
  },
];

export const daftarArtikel: Artikel[] = [
  { id: 1, judul: "Anak Kost Anti Stress! Dzawani Kost Tawarkan Fasilitas Olahraga Gratis!", slug: "anak-kost-anti-stress-dzawani-kost-tawarkan-fasilitas-olahraga-gratis", tanggal: "2024-08-01", kategori: "Tips Kost", ringkasan: "Dzawani Kost hadir dengan fasilitas olahraga gratis untuk penghuni. Simak apa saja fasilitas yang tersedia dan bagaimana cara memanfaatkannya.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/tips-anak-kost.png", penulis: "Tim Dzawani" },
  { id: 2, judul: "5 Cafe Murah Meriah di Jogja untuk Anak Kost, Bisa Nugas di Sini!", slug: "5-cafe-murah-meriah-di-jogja-untuk-anak-kost-bisa-nugas-di-sini", tanggal: "2024-08-01", kategori: "Wisata Jogja", ringkasan: "Rekomendasi cafe murah di Jogja yang cocok untuk anak kost yang ingin ngerjain tugas sambil menikmati suasana kafe.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/Tips-Wisata-di-Jogja-1.png", penulis: "Tim Dzawani" },
  { id: 3, judul: "Info Kost Putri Jogja Free Kolam Renang dan Gym, Harga Sewa Terjangkau!", slug: "info-kost-putri-jogja-free-kolam-renang-dan-gym-harga-sewa-terjangkau", tanggal: "2024-07-31", kategori: "Wisata Jogja", ringkasan: "Temukan kost putri di Jogja yang menawarkan fasilitas kolam renang dan gym gratis dengan harga sewa yang terjangkau.", gambar: "https://dzawanikost.com/wp-content/uploads/2024/07/DSC00571.jpg", penulis: "Tim Dzawani" },
  { id: 4, judul: "Bukan Sembarang Kost, Ini Dia Kos-kosan Bebas di Jogja yang Paling Nyaman", slug: "bukan-sembarang-kost-ini-dia-kos-kosan-bebas-di-jogja-yang-paling-nyaman", tanggal: "2024-07-30", kategori: "Wisata Jogja", ringkasan: "Mencari kos-kosan bebas di Jogja yang nyaman? Berikut rekomendasi terbaik yang bisa kamu pertimbangkan.", gambar: "https://dzawanikost.com/wp-content/uploads/2024/07/DSC00573.jpg", penulis: "Tim Dzawani" },
  { id: 5, judul: "Info Kost Harian Jogja, Bebas dan Elit Cocok untuk Staycation", slug: "info-kost-harian-jogja-bebas-dan-elit-cocok-untuk-staycation", tanggal: "2024-07-29", kategori: "Wisata Jogja", ringkasan: "Ingin staycation di Jogja? Kost harian bebas dan elit ini bisa jadi pilihan terbaik untuk liburanmu.", gambar: "https://dzawanikost.com/wp-content/uploads/2024/07/DSC02849.jpg", penulis: "Tim Dzawani" },
  { id: 6, judul: "Kost Bebas Selalu Jadi Pilihan, Apa yang Paling Digemari?", slug: "kost-bebas-selalu-jadi-pilihan-apa-yang-paling-digemari", tanggal: "2024-07-22", kategori: "Tips Kost", ringkasan: "Kost bebas semakin diminati. Simak apa saja yang membuat kost bebas selalu menjadi pilihan utama anak kost.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/anak-kos.jpg", penulis: "Tim Dzawani" },
  { id: 7, judul: "Perbedaan Kost Eksklusif dan Apartemen: Mana yang Lebih Terjangkau?", slug: "perbedaan-kost-eksklusif-dan-apartemen-mana-yang-lebih-terjangkau", tanggal: "2024-07-17", kategori: "Tips Kost", ringkasan: "Bingung memilih antara kost eksklusif dan apartemen? Simak perbandingan lengkap dari segi harga dan fasilitas.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/4-tips-maba.png", penulis: "Tim Dzawani" },
  { id: 8, judul: "Dzawani Kost Palagan, Solusi Kos-kosan Mewah dengan Harga Terjangkau", slug: "dzawani-kost-palagan-solusi-kos-kosan-mewah-dengan-harga-terjangkau", tanggal: "2024-07-16", kategori: "Tips Kost", ringkasan: "Dzawani Kost Palagan hadir sebagai solusi hunian mewah dengan harga yang masih terjangkau di Yogyakarta.", gambar: "https://dzawanikost.com/wp-content/uploads/2024/04/DSC04539-2-2.jpg", penulis: "Tim Dzawani" },
  { id: 9, judul: "Dzawani Kost Krawitan, Kos-kosan Khusus Putra yang Sejuk dan Nyaman!", slug: "dzawani-kost-krawitan-kos-kosan-khusus-putra-yang-sejuk-dan-nyaman", tanggal: "2024-07-12", kategori: "Tips Kost", ringkasan: "Dzawani Kost Krawitan menawarkan hunian khusus putra yang sejuk, nyaman, dan terjangkau di kawasan Godean.", gambar: "https://dzawanikost.com/wp-content/uploads/2024/05/DSC04722.jpg", penulis: "Tim Dzawani" },
  { id: 10, judul: "Inilah Faktor yang Membuat Harga Sewa Kos-kosan Murah dan Mahal", slug: "inilah-faktor-yang-membuat-harga-sewa-kos-kosan-murah-dan-mahal", tanggal: "2024-07-10", kategori: "Tips Kost", ringkasan: "Apa saja yang menentukan harga sewa kos-kosan? Simak faktor-faktor penting yang mempengaruhi harga kost.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/atur-keuangan-dzawani-indonesia.jpg", penulis: "Tim Dzawani" },
  { id: 11, judul: "Kost Bebas di Jogja Fasilitas Mewah, Boleh Ngapain Aja?", slug: "kost-bebas-di-jogja-fasilitas-mewah-boleh-ngapain-aja", tanggal: "2024-07-08", kategori: "Wisata Jogja", ringkasan: "Kost bebas di Jogja dengan fasilitas mewah kini semakin banyak. Simak apa saja yang boleh dilakukan di kost bebas.", gambar: "https://dzawanikost.com/wp-content/uploads/2024/07/DSC00580.jpg", penulis: "Tim Dzawani" },
  { id: 12, judul: "Anak Kost Simak! Inilah Bahaya Pola Makan dan Pola Tidur yang Tidak Teratur", slug: "anak-kost-simak-inilah-bahaya-pola-makan-dan-pola-tidur-yang-tidak-teratur", tanggal: "2024-07-05", kategori: "Kesehatan", ringkasan: "Pola makan dan tidur yang tidak teratur bisa berdampak buruk bagi kesehatan. Simak bahayanya dan cara mengatasinya.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/050522900_1578016961-Terlalu-Lama-Sendiri-Bikin-Gampang-Sakit-Benarkah-By-kitzcorner-shutterstock.jpg", penulis: "Tim Dzawani" },
  { id: 13, judul: "Ini Dia Kost Paling Bebas di Jogja, Dijamin Betah!", slug: "ini-dia-kost-paling-bebas-di-jogja-dijamin-betah", tanggal: "2024-07-04", kategori: "Wisata Jogja", ringkasan: "Rekomendasi kost paling bebas di Jogja yang dijamin bikin betah. Fasilitas lengkap dengan peraturan yang fleksibel.", gambar: "https://dzawanikost.com/wp-content/uploads/2024/07/DSC02857.jpg", penulis: "Tim Dzawani" },
  { id: 14, judul: "Ngekost Plus Treatment Gratis? Tinggal di Dzawani Kost Aja!", slug: "ngekost-plus-treatment-gratis-tinggal-di-dzawani-kost-aja", tanggal: "2024-06-28", kategori: "Tips Kost", ringkasan: "Dzawani Kost menawarkan program treatment gratis untuk penghuni setia. Simak apa saja keuntungannya.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/12/DSC02849-1.jpg", penulis: "Tim Dzawani" },
  { id: 15, judul: "Alasan Mengapa Kost LV dan Bebas Lebih Banyak Peminat", slug: "alasan-mengapa-kost-lv-dan-bebas-lebih-banyak-peminat", tanggal: "2024-05-31", kategori: "Tips Kost", ringkasan: "Kost LV (Low Voltage) dan bebas semakin diminati. Apa alasan di balik tingginya peminat kost jenis ini?", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/teknologi-dzawani-indoensia.webp", penulis: "Tim Dzawani" },
  { id: 16, judul: "Tips Memilih Kasur untuk Anak Kost Agar Tidur Lebih Nyaman", slug: "tips-memilih-kasur-untuk-anak-kost-agar-tidur-lebih-nyaman", tanggal: "2024-05-31", kategori: "Tips Kost", ringkasan: "Kasur yang tepat bisa meningkatkan kualitas tidur. Simak tips memilih kasur terbaik untuk kamar kost.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/Bargain-8-Medium.jpg", penulis: "Tim Dzawani" },
  { id: 17, judul: "Barang Wajib yang Harus Dimiliki Anak Kost Saat Tinggal Sendiri", slug: "barang-wajib-yang-harus-dimiliki-anak-kost-saat-tinggal-sendiri", tanggal: "2024-05-30", kategori: "Tips Kost", ringkasan: "Apa saja barang yang wajib dimiliki anak kost? Simak daftar lengkap perlengkapan kost yang tidak boleh terlewat.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/tips-anak-kost.png", penulis: "Tim Dzawani" },
  { id: 18, judul: "Info Kos-kosan Khusus Mahasiswi di Jogja Dekat Kampus Amikom", slug: "info-kos-kosan-khusus-mahasiswi-di-jogja-dekat-kampus-amikom", tanggal: "2024-05-29", kategori: "Wisata Jogja", ringkasan: "Rekomendasi kos-kosan khusus mahasiswi di Jogja yang dekat dengan kampus Amikom. Fasilitas lengkap dan harga terjangkau.", gambar: "https://dzawanikost.com/wp-content/uploads/2024/05/DSC02825.jpg", penulis: "Tim Dzawani" },
  { id: 19, judul: "Kontrakan vs Kost Eksklusif, Mana yang Lebih Murah dan Nyaman?", slug: "kontrakan-vs-kost-eksklusif-mana-yang-lebih-murah-dan-nyaman", tanggal: "2024-05-28", kategori: "Tips Kost", ringkasan: "Bingung memilih antara kontrakan dan kost eksklusif? Simak perbandingan lengkap dari segi harga, fasilitas, dan kenyamanan.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/Definisi-Komunitas.jpg", penulis: "Tim Dzawani" },
  { id: 20, judul: "Mengenal Istilah Unik Seputar Anak Kost yang Sering Didengar", slug: "mengenal-istilah-unik-seputar-anak-kost-yang-sering-didengar", tanggal: "2024-05-27", kategori: "Tips Kost", ringkasan: "Ada banyak istilah unik yang sering digunakan anak kost. Simak penjelasan lengkap istilah-istilah tersebut.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/anak-kos.jpg", penulis: "Tim Dzawani" },
  { id: 21, judul: "Promo Khusus Maba, Dzawani Kost Tawarkan Diskon Sampai 150 Ribu!", slug: "promo-khusus-maba-dzawani-kost-tawarkan-diskon-sampai-150-ribu", tanggal: "2024-05-26", kategori: "Tips Kost", ringkasan: "Kabar gembira untuk mahasiswa baru! Dzawani Kost menawarkan promo diskon spesial hingga Rp 150.000 untuk maba.", gambar: "https://dzawanikost.com/wp-content/uploads/2024/04/DSC04582-2-2.jpg", penulis: "Tim Dzawani" },
  { id: 22, judul: "Liburan ke Jogja, Nginep di Dzawani Kost Ngabean Aja!", slug: "liburan-ke-jogja-nginep-di-dzawani-kost-ngabean-aja", tanggal: "2024-05-25", kategori: "Wisata Jogja", ringkasan: "Sedang liburan ke Jogja? Dzawani Kost Ngabean bisa jadi pilihan penginapan yang nyaman dan terjangkau.", gambar: "https://dzawanikost.com/wp-content/uploads/2024/07/DSC00571.jpg", penulis: "Tim Dzawani" },
  { id: 23, judul: "Ada Kado Spesial Khusus Penghuni Dzawani Kost Eksklusif!", slug: "ada-kado-spesial-khusus-penghuni-dzawani-kost-eksklusif-wah-apa-tuh", tanggal: "2024-04-30", kategori: "Tips Kost", ringkasan: "Dzawani Kost memberikan kado spesial untuk penghuni setia. Simak apa saja hadiah menarik yang bisa kamu dapatkan.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/12/DSC02849-1.jpg", penulis: "Tim Dzawani" },
  { id: 24, judul: "Ngekos dengan Fasilitas Kolam Renang di Jogja Emang Ada?", slug: "ngekos-dengan-fasilitas-kolam-renang-di-jogja-emang-ada-nih-kepoin-infonya", tanggal: "2024-04-30", kategori: "Wisata Jogja", ringkasan: "Kost dengan fasilitas kolam renang di Jogja ternyata ada! Simak informasi lengkap dan lokasinya.", gambar: "https://dzawanikost.com/wp-content/uploads/2024/04/DSC04600-2-2.jpg", penulis: "Tim Dzawani" },
  { id: 25, judul: "Atasi Kamar Kost Lembap Agar Tidak Bau, Berikut Tipsnya", slug: "atasi-kamar-kost-lembap-agar-tidak-bau-berikut-tipsnya", tanggal: "2024-04-29", kategori: "Tips Kost", ringkasan: "Kamar kost lembap dan bau? Simak tips ampuh untuk mengatasi masalah ini agar kamar selalu segar dan nyaman.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/DSCF3074.jpg", penulis: "Tim Dzawani" },
  { id: 26, judul: "Jangan Mager! Ini Gerakan Olahraga Sederhana yang Bisa Diterapkan di Kost", slug: "jangan-mager-ini-dia-gerakan-olahraga-sederhana-yang-bisa-diterapkan-di-kost", tanggal: "2024-04-27", kategori: "Kesehatan", ringkasan: "Tidak perlu ke gym! Simak gerakan olahraga sederhana yang bisa dilakukan di dalam kamar kost.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/tips-anak-kost.png", penulis: "Tim Dzawani" },
  { id: 27, judul: "Kebiasaan Baik vs Buruk Anak Kost Saat di Tempat Rantau", slug: "kebiasaan-baik-vs-buruk-anak-kost-saat-di-tempat-rantau-kamu-tipe-yang-mana", tanggal: "2024-04-26", kategori: "Tips Kost", ringkasan: "Ada dua tipe anak kost: yang punya kebiasaan baik dan buruk. Kamu termasuk yang mana? Simak ulasannya.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/ospek-dzawani-indonesia.jpg", penulis: "Tim Dzawani" },
  { id: 28, judul: "Promo Terbatas! Ngekos 3 Bulan Dapat Diskon 150 Ribu di Dzawani Kost!", slug: "promo-terbatas-cuma-di-dzawani-kost-ngekos-3-bulan-dapat-diskon-150-ribu", tanggal: "2024-04-25", kategori: "Tips Kost", ringkasan: "Promo terbatas dari Dzawani Kost! Sewa 3 bulan dan dapatkan diskon Rp 150.000. Jangan sampai ketinggalan!", gambar: "https://dzawanikost.com/wp-content/uploads/2024/04/DSC04617-2-2.jpg", penulis: "Tim Dzawani" },
  { id: 29, judul: "Lebih Baik Asrama Kampus atau Kos-kosan untuk Pilihan Anak Rantau?", slug: "lebih-baik-asrama-kampus-atau-kos-kosan-untuk-pilihan-anak-rantau", tanggal: "2024-04-25", kategori: "Tips Mahasiswa", ringkasan: "Bingung memilih antara asrama kampus dan kos-kosan? Simak perbandingan lengkap untuk membantu keputusanmu.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/4-tips-maba.png", penulis: "Tim Dzawani" },
  { id: 30, judul: "Tips Hemat di Bulan Ramadhan yang Bisa Diterapkan Anak Kost", slug: "tips-hemat-di-bulan-ramadhan-yang-bisa-diterapkan-anak-kost", tanggal: "2024-04-23", kategori: "Keuangan", ringkasan: "Bulan Ramadhan bisa menjadi kesempatan untuk berhemat. Simak tips hemat khusus untuk anak kost selama Ramadhan.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/atur-keuangan-dzawani-indonesia.jpg", penulis: "Tim Dzawani" },
  { id: 31, judul: "Rekomendasi Tempat Ngabuburit di Jogja untuk Anak Kost", slug: "rekomendasi-tempat-ngabuburit-di-jogja-untuk-anak-kost-di-bulan-ramadhan", tanggal: "2024-03-30", kategori: "Wisata Jogja", ringkasan: "Mencari tempat ngabuburit yang asyik di Jogja? Berikut rekomendasi terbaik untuk anak kost selama Ramadhan.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/Tips-Wisata-di-Jogja-1.png", penulis: "Tim Dzawani" },
  { id: 32, judul: "Menu Sahur ala Anak Kost di Bulan Ramadhan, Praktis!", slug: "menu-sahur-ala-anak-kost-di-bulan-ramadhan-praktis", tanggal: "2024-03-29", kategori: "Tips Kost", ringkasan: "Sahur tidak harus ribet! Simak menu sahur praktis dan bergizi yang cocok untuk anak kost selama Ramadhan.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/Bargain-8-Medium.jpg", penulis: "Tim Dzawani" },
  { id: 33, judul: "Menu Buka Puasa Praktis untuk Anak Rantau di Kos-kosan", slug: "menu-buka-puasa-praktis-untuk-anak-rantau-di-kos-kosan", tanggal: "2024-03-28", kategori: "Tips Kost", ringkasan: "Buka puasa di kost tidak harus mahal. Simak menu buka puasa praktis yang bisa dibuat sendiri di kamar kost.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/tips-anak-kost.png", penulis: "Tim Dzawani" },
  { id: 34, judul: "Info Kos-kosan Dekat UPN Jogja, Berikut Rekomendasinya", slug: "info-kos-kosan-dekat-upn-jogja-berikut-rekomendasinya", tanggal: "2024-03-22", kategori: "Wisata Jogja", ringkasan: "Mencari kos-kosan dekat UPN Veteran Yogyakarta? Berikut rekomendasi terbaik yang bisa kamu pertimbangkan.", gambar: "https://dzawanikost.com/wp-content/uploads/2024/09/DSC04771-1.jpg", penulis: "Tim Dzawani" },
  { id: 35, judul: "Begini Tips Menabung Online untuk Pengelolaan Keuangan yang Lebih Efisien", slug: "begini-tips-menabung-online-untuk-pengelolaan-keuangan-yang-lebih-efisien", tanggal: "2024-02-27", kategori: "Keuangan", ringkasan: "Menabung online kini semakin mudah. Simak tips menabung online yang efektif untuk pengelolaan keuangan anak kost.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/atur-keuangan-dzawani-indonesia.jpg", penulis: "Tim Dzawani" },
  { id: 36, judul: "Warna Kamar yang Bikin Nyaman dan Bantu Konsentrasi Anak Kost", slug: "kamar-yang-nyaman-adalah-kamar", tanggal: "2023-07-14", kategori: "Tips Kost", ringkasan: "Pemilihan warna kamar yang tepat bisa meningkatkan konsentrasi dan kenyamanan. Simak rekomendasinya.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/DSCF3074.jpg", penulis: "Tim Dzawani" },
  { id: 37, judul: "Ide Bisnis Sampingan untuk Mahasiswa Tanpa Modal, Tambah Uang Saku!", slug: "ide-bisnis-sampingan-untuk-mahasiswa-tanpa-modal-tambah-uang-saku-dan-bisa-bantu-bayar-kos", tanggal: "2023-07-14", kategori: "Karir & Bisnis", ringkasan: "Mahasiswa bisa punya penghasilan tambahan tanpa modal besar. Simak ide bisnis sampingan yang bisa dicoba.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/teknologi-dzawani-indoensia.webp", penulis: "Tim Dzawani" },
  { id: 38, judul: "Barang Printilan yang Wajib Ada di Kamar Kost, Bermanfaat dan Praktis!", slug: "barang-printilan-yang-wajib-ada-di-kamar-kost-bermanfaat-dan-praktis", tanggal: "2023-07-15", kategori: "Tips Kost", ringkasan: "Ada banyak barang kecil yang sangat bermanfaat di kamar kost. Simak daftar lengkap barang printilan wajib.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/tips-anak-kost.png", penulis: "Tim Dzawani" },
  { id: 39, judul: "Rencana Tinggal di Kost Eksklusif Jogja? Segini Biaya yang Perlu Dipersiapkan", slug: "rencana-tinggal-di-kost-eksklusif-jogja-segini-biaya-yang-perlu-dipersiapkan-oleh-karyawan", tanggal: "2023-07-15", kategori: "Keuangan", ringkasan: "Berencana tinggal di kost eksklusif Jogja? Simak estimasi biaya yang perlu dipersiapkan.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/atur-keuangan-dzawani-indonesia.jpg", penulis: "Tim Dzawani" },
  { id: 40, judul: "Modal Cuma 500 Ribu! Ini 10 Ide Usaha untuk Mahasiswa yang Menguntungkan", slug: "modal-cuma-500-ribu-ini-10-ide-usaha-untuk-mahasiswa-yang-hasilkan-keuntungan-berlimpah", tanggal: "2023-07-20", kategori: "Karir & Bisnis", ringkasan: "Dengan modal hanya Rp 500.000, mahasiswa bisa memulai usaha yang menguntungkan. Simak 10 ide terbaiknya.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/cara-menjadi-dosen-1.jpg", penulis: "Tim Dzawani" },
  { id: 41, judul: "Tips Anti Ngantuk Pas Skripsian, Mahasiswa Semester Akhir Wajib Baca!", slug: "tips-anti-ngantuk-pas-skripsian-mahasiswa-semester-akhir-harus-lakukan-hal-ini", tanggal: "2023-07-21", kategori: "Tips Mahasiswa", ringkasan: "Ngantuk saat mengerjakan skripsi adalah masalah umum. Simak tips ampuh untuk tetap terjaga dan produktif.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/4-tips-maba.png", penulis: "Tim Dzawani" },
  { id: 42, judul: "8 Kesalahan Mahasiswa yang Bikin Skripsi Mandek, Hindari Sekarang!", slug: "8-kesalahan-mahasiswa-yang-bikin-skripsi-mandek-hindari-hal-ini-agar-lulus-tepat-waktu", tanggal: "2023-07-21", kategori: "Tips Mahasiswa", ringkasan: "Skripsi mandek? Mungkin kamu melakukan kesalahan ini. Simak 8 kesalahan umum dan cara menghindarinya.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/cara-menjadi-dosen-1.jpg", penulis: "Tim Dzawani" },
  { id: 43, judul: "Mahasiswa Perlu Waspada! Ini Tanda-tanda Burnout Kuliah yang Ganggu Semangat", slug: "mahasiswa-perlu-waspada-ini-tanda-tanda-burnout-kuliah-yang-ganggu-semangat-belajar", tanggal: "2023-07-21", kategori: "Kesehatan", ringkasan: "Burnout kuliah bisa mengganggu semangat belajar. Kenali tanda-tandanya dan cara mengatasinya.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/050522900_1578016961-Terlalu-Lama-Sendiri-Bikin-Gampang-Sakit-Benarkah-By-kitzcorner-shutterstock.jpg", penulis: "Tim Dzawani" },
  { id: 44, judul: "Tips Hadapi Stres dan Depresi Kuliah, Mahasiswa Harus Hati-hati!", slug: "tips-hadapi-stres-dan-depresi-kuliah-mahasiswa-baru-dan-semester-akhir-harus-hati-hati", tanggal: "2023-08-12", kategori: "Kesehatan", ringkasan: "Stres dan depresi kuliah adalah masalah serius. Simak tips menghadapinya agar tetap sehat mental.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/Definisi-Komunitas.jpg", penulis: "Tim Dzawani" },
  { id: 45, judul: "10 Tips Mengontrol Keuangan ala Mahasiswa, Hidup Hemat Anti Boros!", slug: "tips-mengontrol-keuangan-ala-mahasiswa-hemat-anti-boros", tanggal: "2023-08-14", kategori: "Keuangan", ringkasan: "Mengelola keuangan sebagai mahasiswa memang tidak mudah. Simak 10 tips ampuh untuk hidup hemat dan anti boros.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/atur-keuangan-dzawani-indonesia.jpg", penulis: "Tim Dzawani" },
  { id: 46, judul: "Perbedaan Ngekos di Kost Biasa dan Kost Eksklusif, Lebih Nyaman Mana?", slug: "perbedaan-kost-biasa-dan-kost-ekslusif", tanggal: "2023-08-11", kategori: "Tips Kost", ringkasan: "Apa bedanya kost biasa dan kost eksklusif? Simak perbandingan lengkap dari segi fasilitas dan kenyamanan.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/DSCF3074.jpg", penulis: "Tim Dzawani" },
  { id: 47, judul: "6 Tips Cari Kost Eksklusif Nyaman Tapi Murah Khusus Mahasiswa", slug: "tips-cari-kost-ekslusif-nyaman-tapi-murah-khusus-mahasiswa", tanggal: "2023-08-11", kategori: "Tips Kost", ringkasan: "Mencari kost eksklusif yang nyaman tapi tetap murah? Simak 6 tips jitu untuk menemukan kost impianmu.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/tips-anak-kost.png", penulis: "Tim Dzawani" },
  { id: 48, judul: "Cara Pilih Kost Eksklusif di Jogja Dengan Lokasi yang Strategis", slug: "cara-pilih-kost-eksklusif-di-jogja-dengan-lokasi-yang-strategis", tanggal: "2023-08-15", kategori: "Wisata Jogja", ringkasan: "Lokasi strategis adalah kunci kenyamanan ngekost. Simak cara memilih kost eksklusif di Jogja dengan lokasi terbaik.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/Tips-Wisata-di-Jogja-1.png", penulis: "Tim Dzawani" },
  { id: 49, judul: "10 Tips Menabung dan Alokasi Uang untuk Mahasiswa, Bantu Kontrol Keuangan", slug: "tips-menabung-dan-alokasi-uang-untuk-mahasiswa", tanggal: "2023-08-16", kategori: "Keuangan", ringkasan: "Menabung sejak mahasiswa adalah kebiasaan baik. Simak 10 tips menabung dan alokasi uang yang efektif.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/atur-keuangan-dzawani-indonesia.jpg", penulis: "Tim Dzawani" },
  { id: 50, judul: "Hits Abis! Rekomendasi Tempat Nongkrong Asik di Jogja Andalan Mahasiswa", slug: "yogyakarta", tanggal: "2023-07-10", kategori: "Wisata Jogja", ringkasan: "Jogja punya banyak tempat nongkrong hits yang wajib dikunjungi. Simak rekomendasi terbaik untuk mahasiswa dan wisatawan.", gambar: "https://dzawanikost.com/wp-content/uploads/2022/06/Tips-Wisata-di-Jogja-1.png", penulis: "Tim Dzawani" },
];

export const lokasiList = ["Yogyakarta", "Bandung", "Jakarta", "Bali"];
export const kotaList = ["Yogyakarta", "Bandung", "Jakarta", "Bali"];
export const penghuniList = ["Putra", "Putri"];
export const periodeSewa = ["1 Bulan", "3 Bulan", "6 Bulan"];
export const kategoriArtikel = ["Semua", "Tips Kost", "Wisata Jogja", "Tips Mahasiswa", "Keuangan", "Kesehatan", "Karir & Bisnis"];

export const fasilitasUmum = [
  { icon: "wifi", label: "WiFi Gratis", deskripsi: "Internet cepat 24 jam" },
  { icon: "parking", label: "Parkir Luas", deskripsi: "Motor & mobil" },
  { icon: "security", label: "Keamanan 24 Jam", deskripsi: "CCTV & satpam" },
  { icon: "laundry", label: "Laundry", deskripsi: "Layanan cuci kiloan" },
  { icon: "kitchen", label: "Dapur Bersama", deskripsi: "Lengkap & bersih" },
  { icon: "mosque", label: "Mushola", deskripsi: "Fasilitas ibadah" },
];

export const formatHarga = (harga: number): string => {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(harga);
};
